# -*- coding: utf-8 -*-
""".ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/saepin/73da6918c56a60fb1148995ecbd4f77d/.ipynb
"""

def total():
  price1 = 100
  price2 = 200
  tax = 1.1
  return price1 + price2*tax

print (total())