# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kd233vir3ur3Z_nqu_erZVAy7l2rziuC
"""

number1=10
number2=20
number3=5
user_name="cm"
print((number1+number2)*number3/2)
print(user_name)