# -*- coding: utf-8 -*-
"""練習

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-sBhgIWDEMEqz_Hs73Z_nfxh0YfvERHg
"""

print(45+18)

for ver in range(1,101):
   if ver % 3 == 0 and ver % 5 == 0:
    print("FIZBUZZ")
   elif ver % 3 ==0:
       print("Fizz")
   elif ver % 5 ==0:
       print("BUZZ")
   else:
      print(ver)

print(45>18)

import random
num=random.randint(0,4)
print(num)
if num==4:
  print("大当たりです")