# -*- coding: utf-8 -*-
"""課題8

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iRngAIsdQ3vQqetP70_Rtz46QeQNxzqd
"""

list=["水","金","土","火","木","土","天","海","冥"]
for list in list:
    print(list)