# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kd233vir3ur3Z_nqu_erZVAy7l2rziuC
"""

upperside=10
lowerside=20
hight=5
unit="cm"
print(str((upperside+lowerside)*hight/2)+unit)